import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Iosevka_Charon,
  Jura,
  Playfair_Display,
  Judson,
} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const iosevkaCharon = Iosevka_Charon({
  variable: "--font-iosevka-charon",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const jura = Jura({
  variable: "--font-jura",
  subsets: ["latin"],
});

const judson = Judson({
  variable: "--font-judson",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${iosevkaCharon.variable} ${jura.variable} ${judson.variable} ${playfairDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
